[package]
name = "dioxus-resize-observer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Resize observer hooks for Dioxus."

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-signals = { git = "https://github.com/dioxuslabs/dioxus" }
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["ResizeObserver", "ResizeObserverEntry"] }
dioxus-use-mounted = { git = "https://github.com/matthunz/dioxus-use-mounted" }
